# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_location_admin_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='admin_level',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='country_code',
            new_name='division_id'
        ),
    ]
