# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-14 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About', max_length=100)),
                ('text', models.TextField()),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'About page',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Countries', max_length=100)),
                ('text', models.TextField()),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'Countries page',
            },
        ),
        migrations.CreateModel(
            name='CountryLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CountryOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, upload_to=pages.models.filepath, verbose_name='upload an image for this country')),
                ('background', models.TextField()),
                ('first_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_link', to='pages.CountryLink')),
                ('second_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_link', to='pages.CountryLink')),
                ('third_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_link', to='pages.CountryLink')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Frequently Asked Questions', max_length=100)),
                ('text', models.TextField()),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'FAQ page',
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Help', max_length=100)),
                ('text', models.TextField()),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'Help page',
            },
        ),
    ]
