# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-25 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_remove_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='personname',
            name='value_ar',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='personname',
            name='value_en',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='personname',
            name='value_es',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='personname',
            name='value_fr',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
